### ISSUE TITLE
Rule instance up/down arrows don't always work

### ISSUE THREAD

**Issue by daledavies** [daledavies/moodle-tool_registrationrules#21]
Add a few instances, delete a few, then try to move some around.

**Comment by phager-at** [comment]
Yes, due to our limited time, it was never implemented at all… at least in rule_instances_controller there's just the methods prepared, but no logic actually moving the instances around.

See (nearly empty methods):
- `tool_registrationrules\local\rule_instances_controller::move_instance_up()` and
- `tool_registrationrules\local\rule_instances_controller::move-instance_down()`
