### ISSUE TITLE
Standardise on flexible_table for instance settings page?

### ISSUE THREAD

**Issue by daledavies** [daledavies/moodle-tool_registrationrules#7]
I'm wondering if we should use the core `flexible_table` class here rather than building the table in a template, would be more in line with core? 

This is also used in the registration rules plugin management page as I copied most of that from the core assignment submission plugin management page.

**Comment by daledavies** [comment]
Further to this I feel we should use `flexible_table` but then be strict about not using `html_writer`, so any html to go inside a table cell should use mustache.

Because of this we should consider...

- replacing uses of `html_writer` in the registration rules plugin management page with mustache
- migrating the rules instances management page to use `flexible_table`

What do you think?

**Comment by daledavies** [comment]
An alternative for the registration rules plugin management page might be to use `admin_setting_manage_plugins`, I've only just discovered this exists!

**Comment by phager-at** [comment]
IMHO `html_writer` and `flexible_table` seems a little bit on the legacy side nowadays.
Also we won't need much of the functionality of `flexible_table`, as we're not sorting the table, using collapsible columns, or exporting it as CSV/PDF/whatever.

For the plugin management page it seems promising to extend `admin_setting_manage_plugins`!

An approach may being more up to date with recent Moodle code may be to use a reactive UI instead, thus rendering the components with templates. It may be a bit of overkill, but I'l always like a nice UI on the backside too—admins deserve a beautiful interface. :-)

It depends on how much time we're investing into it, but to me preferred low-budget approach would be:
- `admin_setting_manage_plugins` for the sub plugin management
- simple table rendered via mustache template for rule instance management (we may also make an non-writing-admin setting class of it, so we can display it directly on regular admin pages instead of an external one)

**Comment by daledavies** [comment]
Done with PR #26
